routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});



Route::resource('shows','ShowController');

app/Show.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Show extends Model
{
    public $timestamps = false;
    
    protected  $fillable = array('nome', 'genero', 'local', 'artista', 'valor', 'publico');
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ShowController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Show;

class ShowController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       $show = Show::all();
       return view('shows_lista', compact('show'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        
        
        $acao = 1;
        
        return view('shows_form', compact('acao'));
        
        
        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $dados = $request->all();
        
        $s = Show::create($dados);
        if($s){
            
            return redirect()->route('shows.index')
                    ->with('status', $request->nome.'Cadastrado com sucesso');
            
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $s = new Show();
        $reg = $s ->find($id);
        
        $acao = 3;
        return view('shows_form', compact('reg','acao'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $s = new Show();
        
        $reg = $s->find($id);
        
        $acao = 2;
        
        return view('shows_form', compact('reg', 'acao'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $reg = Show::find($id);
        $dados = $request->all();
        $alterado = $reg->update($dados);
        
        if($alterado){
            return redirect()->route('shows.index')
                    ->with('status', $request->nome.'Aterado com sucesso');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $s = Show::find($id);
        if($s->delete()){
            return redirect()->route('shows.index')->with('status', $s->nome . 'Excluido com sucesso');
        }
    }
}

resources/views/index.blade.php
@extends('principal')
@section('conteudo')


<div class='col-sm-7'>
    <img src="Show.jpg" alt="Show">
    
</div>
<div class="col-sm-5">
    <h2>Seja Bem-Vindo à Show Maneger</h2>
    <h4>Contato: (53) 99101.0203</h4>
</div>

@endsection

resources/views/principal.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Shows Maneger</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">Show Maneger</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="{{url('/')}}">Home</a></li>
      <li><a href="{{route('shows.index')}}">Cadastro</a></li>
      <li><a href="#">Pesquisas</a></li>
      <li><a href="#">Relatórios</a></li>
    </ul>
  </div>
</nav>
  
<div class="container">
@yield('conteudo')
</div>

</body>
</html>

resources/views/shows_form.blade.php
@extends('principal')
@section('conteudo')

 <div class="row">
  <div class="col-sm-11">
      <h2>
     @if($acao == 1)
     Inclusão 
     @elseif($acao == 2)
     Alteração 
     @elseif($acao == 3)
     Vizualização
     @endif
       de Shows
      </h2>
  </div>
  <div class="col-sm-1"><a href="{{route('shows.index')}}" class="btn btn-primary" role="button">Voltar</a></div>  
</div>

@if($acao == 1)
<form method="post" action='{{route('shows.store')}}'>
    
   @elseif($acao == 2)
   <form method="post" action='{{route('shows.update',$reg->id)}}'>
 {!! method_field('PUT') !!}
@endif
{{csrf_field()}}
       
       
       <div class="form-group">
    <label for="nome">Nome do Show:</label>
    <input type="text" class="form-control" id="nome" name="nome" placeholder="Nome do show" value="{{$reg->nome or old('nome')}}">
  </div>

<div class="form-group">
    <label for="genero">Genero:</label>
    <input type="text" class="form-control" id="genero" name="genero" placeholder="genero" value="{{$reg->genero or old('genero')}}">
  </div>    
    
    <div class="form-group">
    <label for="local">Local:</label>
    <input type="text" class="form-control" id="local" name="local" placeholder="local" value="{{$reg->local or old('local')}}">
  </div>
    
    <div class="form-group">
    <label for="artista">Artista:</label>
    <input type="text" class="form-control" id="artista" name="artista" placeholder="artista" value="{{$reg->artista or old('artista')}}">
  </div>
    
<div class="form-group">
    <label for="valor">Valor:</label>
    <input type="text" class="form-control" id="valor" name="valor" placeholder="valor" value="{{$reg->valor or old('valor')}}">
  </div>


<div class="form-group">
    <label for="publico">Publico:</label>
    <input type="text" class="form-control" id="publico" name="publico" placeholder="publico" value="{{$reg->publico or old('publico')}}">
  </div>

@if($acao == 1 || $acao == 2)

    <button type="submit" class="btn btn-primary">Enviar</button>
    <button type="reset" class="btn btn-warning">Limpar</button>
    
    @endif
</form>
        
@endsection

resources/views/shows_lista.blade.php
@extends('principal')
@section('conteudo')

<div class="col-sm-11">
    <h2>Listagem de Shows</h2>
</div>

<div class="col-sm-1">
    <a href="{{route('shows.create')}}" class="btn btn-primary" role="button">Novo</a>
</div>

<div class="col-sm-12">
 <table class="table table-hover">
    <thead>
      <tr>
        <th>Código</th>
        <th>Show</th>
        <th>Genero</th>
        <th>Local</th>
        <th>Artista/Banda</th>
        <th>Valor R$</th>
        <th>Publico</th>
        <th>Renda R$</th>
        <th>Ação</th>
        
      </tr>
    </thead>
    
    <tbody>
        @foreach($show as $shows)
        <tr>
            
            <td>{{$shows->id}}</td>
            <td>{{$shows->nome}}</td>
            <td>{{$shows->genero}}</td>
            <td>{{$shows->local}}</td>
            <td>{{$shows->artista}}</td>
            <td>{{number_format($shows->valor, '2', ',' , '.')}}</td>
            <td>{{$shows->publico}}</td>
            <td>{{number_format((number_format($shows->valor, '2', ',', '.'))*($shows->publico),'2',',','.')}}</td>
            
           <td>
                <a href="{{route('shows.show' , $shows->id)}}" class="btn btn-info" role="button">Ver</a></div>
                <a href="{{route('shows.edit' , $shows->id)}}" class="btn btn-warning" role="button">Alterar</a></div>
<form style="display: inline-block;" method="POST" action="{{route('shows.destroy', $shows->id)}}"
            onsubmit="return confim('Confirma a exclusão?')">
                {{method_field('DELETE')}}
                {{csrf_field()}} 
<button type="submit" class="btn btn-danger">Excluir</button>
            </form>

                          


            </td>
            
            
        </tr>
     
    </tbody>
    @endforeach
  </table>
</div>

@endsection